name: crabnet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pytorch>=1.7
  - cudatoolkit==11.3.*
  - tqdm
  - joblib
  - psutil
  - conda-souschef